import type { Metadata } from "next";
import "@/styles/style.scss";
import Header from "@/components/common/Header";
import { Suspense } from "react";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Suspense fallback={<div></div>}>
          <Header />
        </Suspense>
        {children}
      </body>
    </html>
  );
}
